# Step 1: Build the React application
FROM node:latest as build
WORKDIR /app
COPY ../frontend/package.json ./
COPY ../frontend/package-lock.json ./
RUN npm install
COPY ../frontend ./
RUN npm run build

# Step 2: Serve the application using a server like Nginx
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY ../frontend/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
