version: '3'

services:
  order-service:
    build:
      context: .
      dockerfile: orderService/Dockerfile-order

    ports:
      - "2553:2553"
    networks:
      - foodie-network

  restaurant-service:
    build:
      context: .
      dockerfile: restaurantService/Dockerfile-restaurant
    networks:
      - foodie-network

    ports:
      - "2551:2551"

  payment-service:
    build:
      context: .
      dockerfile: paymentService/Dockerfile-payment
    networks:
      - foodie-network

    ports:
      - "2555:2555"

  delivery-service:
    build:
      context: .
      dockerfile: deliveryService/Dockerfile-delivery
    networks:
      - foodie-network

    ports:
      - "2554:2554"

networks:
  foodie-network:
    driver: bridge