version: '3'

services:
#  front-end:
#    build:
#      context: .
#      dockerfile: frontend/Dockerfile-frontend
#
#    ports:
#      - "3000:3000"
#    networks:
#      - foodie-network

  order-service:
    build:
      context: .
      dockerfile: orderService/Dockerfile-order

    ports:
      - "2553:2553"
      - "8081:8081"
    networks:
      - foodie-network

  restaurant-service:
    build:
      context: .
      dockerfile: restaurantService/Dockerfile-restaurant
    networks:
      - foodie-network

    ports:
      - "2551:2551"
      - "8080:8080"

  payment-service:
    build:
      context: .
      dockerfile: paymentService/Dockerfile-payment
    networks:
      - foodie-network

    ports:
      - "2555:2555"
      - "8084:8084"

  delivery-service:
    build:
      context: .
      dockerfile: deliveryService/Dockerfile-delivery
    networks:
      - foodie-network

    ports:
      - "2554:2554"
      - "8083:8083"

networks:
  foodie-network:
    driver: bridge