apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: delivery-service
  name: delivery-service
spec:
  ports:
    - name: "2554"
      port: 2554
      targetPort: 2554
    - name: "8083"
      port: 8083
      targetPort: 8083
  selector:
    io.kompose.service: delivery-service
status:
  loadBalancer: {}
