apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: delivery-service
  name: delivery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: delivery-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/foodie-foodie-network: "true"
        io.kompose.service: delivery-service
    spec:
      containers:
        - image: delivery-service
          name: delivery-service
          ports:
            - containerPort: 2554
              hostPort: 2554
              protocol: TCP
            - containerPort: 8083
              hostPort: 8083
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
